fixtures:
  repositories:
    sysctl: https://github.com/hercules-team/augeasproviders_sysctl
    augeasproviders_core: https://github.com/hercules-team/augeasproviders_core
    stblib: https://github.com/puppetlabs/puppetlabs-stdlib

