---
.gitignore:
  paths:
    - '/.kitchen/'
    - '/test/fixtures/.librarian/'
    - '/test/fixtures/.tmp/'
    - '/test/fixtures/Puppetfile.lock'
    - '/kitchen.local.yml'

.gitlab-ci.yml:
  delete: true

.pdkignore:
  paths:
    - '/.kitchen/'
    - '/test/fixtures/.librarian/'
    - '/test/fixtures/.tmp/'
    - '/test/fixtures/Puppetfile.lock'

.rubocop.yml:
  default_configs:
    inherit_from: .rubocop_todo.yml

.travis.yml:
  delete: true

.yardopts:
  delete: true

appveyor.yml:
  delete: true

Gemfile:
  required:
    ':integration':
      - gem: 'librarian-puppet'
      - gem: 'test-kitchen'
      - gem: 'kitchen-digitalocean'
      - gem: 'kitchen-docker'
        git: 'https://github.com/mcgege/kitchen-docker'
        branch: 'leap15'
      - gem: 'kitchen-inspec'
      - gem: 'kitchen-puppet'
      - gem: 'kitchen-sync'
      - gem: 'inspec'
        source: 'https://packagecloud.io/cinc-project/stable'
      - gem: 'inspec-core'
        source: 'https://packagecloud.io/cinc-project/stable'
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '~> 1.15'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"

Rakefile:
  changelog_user: 'dev-sec'
  changelog_project: 'puppet-os-hardening'
  changelog_since_tag: '1.1.1'
  imports:
    - 'Rakefile.local'

data/common.yaml:
  delete: true

hiera.yaml:
  delete: true

spec/default_facts.yml:
  extra_facts:
    retrieve_system_users: 'root,bin,daemon,adm,lp,sync,shutdown,halt,mail,operator,games,ftp,nobody,systemd-network,dbus,polkitd,rpc,rpcuser,postfix,sshd,chrony'
    home_users: ''

spec/spec_helper.rb:
  mock_with: ':rspec'

